### ISSUE TITLE
WinForms

### ISSUE THREAD

**Issue by tojosmarce** [BRomeroT/MVVMUniversal#2]
Hola Benjamín, seguí tu conferencia en .NET Conf Latinoamérica 2020 - Día 1 y ahora he comenzado a revisar tu código a detalle y me parece un aporte espectacular. Quería saber si me podrías ayudar con dos temas, primero, si se podría utilizar para una View que sea Windows Form, y si es así, de pronto me podrías ayudar cómo sería su utilización considerando el ejemplo que has realizado del login con Blazor y Xamarin.

Muchas gracias desde ya.

**Comment by BRomeroT** [comment]
En teoría debería de podese enlazar, pues usarías Object Data Source, los eventos si tendrías que cacharlos y ejecutar los comandos, pero lo habilitado podrías enlazarlos a las propiedades de ejecución del comando.

Honestamente tiene muchos años que no uso Windows Forms, pero suena interesante hacer la prueba como te comento.

**Comment by BRomeroT** [comment]
Listo, puedes continuar con la implementación para Windows Forms.

Te dejo las bases en el [commit](https://github.com/BRomeroT/MVVMUniversal/commit/771a5ed639e0346c9eff4d99cf7adf65d6a0e2d8)

La debes de implementar el Settings para Windows Forms, así como un modelo de navegación, ya sea en un MDIForm o abrir y cerrar ventanas.

**Comment by tojosmarce** [comment]
Muchas gracias Benjamín.
